### ISSUE TITLE
Failed to build a full subspace node

### ISSUE THREAD

**Issue by xli-cube** [subspace/space-acres#212] opened 2024-06-28 11:00 UTC
<img width="832" alt="image" src="https://github.com/subspace/space-acres/assets/161856328/10cfe0dc-e007-408e-bd87-0e6524f1508c">

**Comment by nazar-pc** [comment] 2024-06-28 11:07
Can you attach logs and tell be at least something about what happened before you got into this situation?

**Comment by xli-cube** [comment] 2024-06-29 02:28
Acres have been disappearing frequently in the past two weeks, until yesterday when I discovered an error.
CPU: i9-14900k (I used frequency reduction software and have blocked Intel's bugs)
[space-acres.zip](https://github.com/user-attachments/files/16038516/space-acres.zip)

**Comment by xli-cube** [comment] 2024-06-29 03:14
I copied the node folder from another computer and solved the problem

**Comment by nazar-pc** [comment] 2024-06-29 11:04
Well, yes, unstable hardware may cause unrecoverable database corruption. Generally I wouldn't recomment copying database from another node though, Space Acres is already using Snap sync and should be able to sync node from scratch in less than an hour.

Looks like the problem is resolved, so I'll close this issue.

**Closed by nazar-pc** 2024-06-29 11:04 UTC
