### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by zsvvv** [subspace/space-acres#117] opened 2024-02-05 15:06 UTC
The Windows version of ACRES has a 4T drive attached, but the memory usage is over 70g, so it should not use so much memory. What is the problem? My computer has not opened any other software except for ACRES

**Comment by nazar-pc** [comment] 2024-02-05 15:10
This is actually not specific to Space Acres and happens with `subspace-farmer` as well. No idea why it happens yet, but we are discussing it in https://forum.subspace.network/t/fake-display-of-high-ram-usage-or-ram-leak-on-windows-by-subspace-farmer/2354?u=nazar-pc

Once it is fixed in `subspace-farmer`, it will also be fixed here automatically.

Are you running 3h (0.1.0 or newer) BTW?

**Comment by zsvvv** [comment] 2024-02-06 07:37
> 您是否运行了 3 小时（0.1.0 或更高版本）？

A computer that has been running for 3 hours has very little space, and it is not clear whether the memory will be heavily occupied. It has been found that the ones that consume a large amount of memory are 3g's 0,0.24.

**Comment by nazar-pc** [comment] 2024-02-06 08:52
Okay, we have updated Rust toolchain in 3h, so I was curious if things have changed. Probably not.

**Comment by zsvvv** [comment] 2024-02-16 02:12
> 好的，我们在 3 小时内更新了 Rust 工具链，所以我很好奇事情是否发生了变化。可能不会。

Version 0.1.1 still consumes a lot of memory

**Comment by nazar-pc** [comment] 2024-02-16 09:20
> Version 0.1.1 still consumes a lot of memory

Of course it does, the issue is still open

**Comment by zsvvv** [comment] 2024-02-16 09:38
> > 0.1.1版本仍然消耗大量内存
> 
> 当然可以，问题仍然存在

We really need to be able to share a node on the local area network like CLI, and we hope this day arrives soon. Because of your GUI version, more people can participate because for beginners, cli is too difficult. Thank you for your work

**Closed** 2024-03-03 13:24 UTC
Labels: bug, ux, farmer
