### ISSUE TITLE
v0.1.20  ERROR Farmer while open app

### ISSUE THREAD

**Issue by kidcdf** [subspace/space-acres#201] opened 2024-05-24 03:55 UTC
![捕获](https://github.com/subspace/space-acres/assets/57767063/6c2a505f-52b8-40f6-97b1-f9fcb39f20f2)
2024-05-24T03:30:02.587657Z ERROR Farmer:{farm_index=3}: space_acres::backend::farmer: Single disk creation failed error=Genesis hash of farm 01HTMMH0KK735BYE769DA3JWT6 67c603c4c71142688fe628b54c1954c8af90d13c4eafd58b1d8decb5c1d1c46a is different from 0c121c75f4ef450f40619e1fca9d1e8e7fbabc42c895bc4790801e85d5a91c34 when farm was created, it is not possible to use farm on a different chain

**Comment by nazar-pc** [comment] 2024-05-24 04:45
Looks like the node path points to a very old Gemini 3d directory, is that possible?

**Comment by nazar-pc** [comment] 2024-05-24 06:05
This was a regression fixed in 0.1.21 that is currently being built. Thanks for reporting and sorry for this.

**Closed by nazar-pc** 2024-05-24 06:05 UTC
Labels: bug
